apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod1
  namespace: eunji
  labels:
    app: my-nginx
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
     - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod2
  namespace: eunji
  labels:
    app: my-nginx
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
      - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: eunji
spec:
  type: NodePort
  selector:
    app: my-nginx
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30303

